### ISSUE TITLE
~10/26 . 공공데이터 API 결과 비교

### ISSUE THREAD

**Issue by 2daebong** [Helibrothers/FOODFANG_CENTRAL_CITY#1]
## 대상
- kamis
- 공공데이터포털

## 조회 조건
- 날짜 : 10/25  
- 대상 : 배추, 파, 양파

데이터에 대한 API 결과 조사 및 비교

# 결론
공공데이터 사용

**Comment by 2daebong** [comment]
http://www.kamis.or.kr/service/price/xml.do?action=dailyPriceByCategoryList&p_cert_key=b7f45085-f18f-4cf6-8f95-0f6213768c82&p_cert_id=2daebong&p_returntype=json&p_product_cls_code=02&p_item_category_code=200&p_country_code=2100&p_regday=2017-10-24&p_convert_kg_yn=N

**Comment by 2daebong** [comment]
item: [
{
item_name: "배추",
kind_name: "고랭지(1kg)",
rank: "상품",
day1: "당일 (10/24)",
dpr1: "600",
day2: "1일전 (10/23)",
dpr2: "600",
day3: "1주일전 (10/17)",
dpr3: "700",
day4: "2주일전 (10/10)",
dpr4: "1,200",
day5: "1개월전",
dpr5: "1,525",
day6: "1년전",
dpr6: "840",
day7: "일평년",
dpr7: "600"
},
{
item_name: "배추",
kind_name: "고랭지(1kg)",
rank: "중품",
day1: "당일 (10/24)",
dpr1: "500",
day2: "1일전 (10/23)",
dpr2: "500",
day3: "1주일전 (10/17)",
dpr3: "500",
day4: "2주일전 (10/10)",
dpr4: "1,000",
day5: "1개월전",
dpr5: "1,325",
day6: "1년전",
dpr6: "640",
day7: "일평년",
dpr7: "473"
},
{
item_name: "배추",
kind_name: "가을(1kg)",
rank: "상품",
day1: "당일 (10/24)",
dpr1: "600",
day2: "1일전 (10/23)",
dpr2: "600",
day3: "1주일전 (10/17)",
dpr3: "-",
day4: "2주일전 (10/10)",
dpr4: "-",
day5: "1개월전",
dpr5: "-",
day6: "1년전",
dpr6: "-",
day7: "일평년",
dpr7: "-"
},
{
item_name: "배추",
kind_name: "가을(1kg)",
rank: "중품",
day1: "당일 (10/24)",
dpr1: "500",
day2: "1일전 (10/23)",
dpr2: "500",
day3: "1주일전 (10/17)",
dpr3: "-",
day4: "2주일전 (10/10)",
dpr4: "-",
day5: "1개월전",
dpr5: "-",
day6: "1년전",
dpr6: "-",
day7: "일평년",
dpr7: "-"
},

**Comment by 2daebong** [comment]
item_name: "양파",
kind_name: "양파(20kg)",
rank: "상품",
day1: "당일 (10/24)",
dpr1: "25,000",
day2: "1일전 (10/23)",
dpr2: "25,000",
day3: "1주일전 (10/17)",
dpr3: "25,000",
day4: "2주일전 (10/10)",
dpr4: "25,000",
day5: "1개월전",
dpr5: "25,250",
day6: "1년전",
dpr6: "19,000",
day7: "일평년",
dpr7: "19,667"
},
{
item_name: "양파",
kind_name: "양파(20kg)",
rank: "중품",
day1: "당일 (10/24)",
dpr1: "21,000",
day2: "1일전 (10/23)",
dpr2: "21,000",
day3: "1주일전 (10/17)",
dpr3: "21,000",
day4: "2주일전 (10/10)",
dpr4: "21,000",
day5: "1개월전",
dpr5: "21,250",
day6: "1년전",
dpr6: "16,000",
day7: "일평년",
dpr7: "17,333"
},
{
item_name: "양파",
kind_name: "수입(20kg)",
rank: "중품",
day1: "당일 (10/24)",
dpr1: "18,000",
day2: "1일전 (10/23)",
dpr2: "18,000",
day3: "1주일전 (10/17)",
dpr3: "18,000",
day4: "2주일전 (10/10)",
dpr4: "18,000",
day5: "1개월전",
dpr5: "18,000",
day6: "1년전",
dpr6: "-",
day7: "일평년",
dpr7: "-"
},

**Comment by 2daebong** [comment]
{
item_name: "파",
kind_name: "대파(1kg)",
rank: "상품",
day1: "당일 (10/24)",
dpr1: "1,600",
day2: "1일전 (10/23)",
dpr2: "1,600",
day3: "1주일전 (10/17)",
dpr3: "1,900",
day4: "2주일전 (10/10)",
dpr4: "2,000",
day5: "1개월전",
dpr5: "2,000",
day6: "1년전",
dpr6: "2,200",
day7: "일평년",
dpr7: "1,708"
},
{
item_name: "파",
kind_name: "대파(1kg)",
rank: "중품",
day1: "당일 (10/24)",
dpr1: "1,200",
day2: "1일전 (10/23)",
dpr2: "1,200",
day3: "1주일전 (10/17)",
dpr3: "1,600",
day4: "2주일전 (10/10)",
dpr4: "1,700",
day5: "1개월전",
dpr5: "1,700",
day6: "1년전",
dpr6: "1,900",
day7: "일평년",
dpr7: "1,475"
},

**Comment by jason-hwang** [comment]
Goooood

**Comment by jason-hwang** [comment]
근데 같은 양파 20kg 라도 중품, 상품이 다른거 같은데 구분하는 유니크 코드가 있나요??

**Comment by jason-hwang** [comment]
중품/상품이 quality 말하는거 맞죠?

**Comment by probitanima11** [comment]
# 공공데이터 
## 조건
부산엄궁농산물도매시장 : 210001 (구시장코드)
부산반여농산물도매시장 : 210009 (구시장코드)
[시장코드.txt](https://github.com/Helibrothers/FOODFANG_CENTRAL_CITY/files/1414754/default.txt)

배추 : 1001
양파 : 1201
대파 : 1202
[품목코드.txt](https://github.com/Helibrothers/FOODFANG_CENTRAL_CITY/files/1414756/default.txt)

## 결과
[result.xlsx](https://github.com/Helibrothers/FOODFANG_CENTRAL_CITY/files/1414819/result.xlsx)

**Comment by probitanima11** [comment]
# kamis
[kamis_result.xlsx](https://github.com/Helibrothers/FOODFANG_CENTRAL_CITY/files/1417988/kamis_result.xlsx)

**Comment by 2daebong** [comment]
@jason-hwang 
_근데 같은 양파 20kg 라도 중품, 상품이 다른거 같은데 구분하는 유니크 코드가 있나요??_
=> 유니크 코드 없는 것 같음. 새로 정의해야 할 듯

_중품/상품이 quality 말하는거 맞죠?_
=> 응 맞아

@probitanima11 
결과 정리 감사.
근데 가격비교를 해봐야 하는데 엑셀만 봐서는 비교가 쉽지 않을 것 같은데 
저 엑셀이 비교 된 결과는 아니지?
